package vistas;

import modelo.*;

public class FormularioArtistas extends javax.swing.JInternalFrame {

    private Spotify s;

    public FormularioArtistas(Spotify s) {
        this.s = s;
        initComponents();
        this.lstArtistas.setListData(this.s.getArtistas().toArray());
        
        for (Discografica d : this.s.getDiscograficas())
            this.cmbDiscograficas.addItem(d);
        
        this.cmbDiscograficas.setSelectedItem(null);
        this.btnAgregarDiscografica.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstArtistas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblAlbumes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbDiscograficas = new javax.swing.JComboBox<>();
        btnAgregarDiscografica = new javax.swing.JButton();
        lblDiscograficas = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Gestión de artistas");
        setMaximumSize(new java.awt.Dimension(440, 350));
        setMinimumSize(new java.awt.Dimension(440, 350));
        setPreferredSize(new java.awt.Dimension(440, 350));

        lstArtistas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstArtistas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                artistaSeleccionado(evt);
            }
        });
        jScrollPane1.setViewportView(lstArtistas);

        jLabel1.setText("Nombre");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArtista(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoArtista(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlbumes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlbumes, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Discográficas");

        btnAgregarDiscografica.setText("Agregar");
        btnAgregarDiscografica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDiscografica(evt);
            }
        });

        lblDiscograficas.setBackground(new java.awt.Color(0, 0, 0));
        lblDiscograficas.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscograficas.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar))
                            .addComponent(txtNombre)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 174, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbDiscograficas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregarDiscografica))
                            .addComponent(lblDiscograficas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEliminar, btnGuardar, btnNuevo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnNuevo)
                            .addComponent(btnEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDiscograficas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDiscograficas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarDiscografica))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarArtista(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArtista
        // si la lista está vacía
        if (this.lstArtistas.isSelectionEmpty()) {
            // creo un artista
            this.s.crearArtista(this.txtNombre.getText());
        } else {
            // modifico un artista
            Artista a = (Artista) this.lstArtistas.getSelectedValue();                
            this.s.modificarArtista(a, this.txtNombre.getText());
        }

        limpiar();
    }//GEN-LAST:event_guardarArtista

    private void nuevoArtista(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoArtista
        limpiar();
    }//GEN-LAST:event_nuevoArtista

    private void artistaSeleccionado(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_artistaSeleccionado
        // verificamos que la lista tenga un item seleccionado
        if (! this.lstArtistas.isSelectionEmpty()) {
            // obtengo el item seleccionado
            Artista a = (Artista) this.lstArtistas.getSelectedValue();
            // asigno los valores de los atributos a las caja de texto
            this.txtNombre.setText( a.getNombre() );

            String albumes = "<html>ÁLBUMES:<ul>";

            for (Album al: a.getAlbumes())
                albumes += "<li> " + al.getNombre() + "</li>";
            
            albumes += "</ul></html>";

            this.lblAlbumes.setText(albumes);
            
            this.lblDiscograficas.setText( a.getDiscograficas().toString() );
            this.btnAgregarDiscografica.setEnabled(true);
        } else {
            this.btnAgregarDiscografica.setEnabled(false);
        }
    }//GEN-LAST:event_artistaSeleccionado

    private void agregarDiscografica(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDiscografica
        Discografica d = (Discografica) this.cmbDiscograficas.getSelectedItem();
        Artista a = (Artista) this.lstArtistas.getSelectedValue();
        this.s.relacionar(a, d);
        
        Spotify.getPersistencia().refrescar(this.s);
        this.lblDiscograficas.setText( a.getDiscograficas().toString() );
    }//GEN-LAST:event_agregarDiscografica

    private void limpiar() {
        // limpio las cajas de texto
        this.txtNombre.setText("");
        this.lblAlbumes.setText("");
        this.lblDiscograficas.setText("");
        System.out.println("Refrescar...");
        Spotify.getPersistencia().refrescar(this.s);
        System.out.println("Refrescado");
        // pueblo la lista
        this.lstArtistas.setListData(this.s.getArtistas().toArray());        
        // deselecciono la lista
        this.lstArtistas.clearSelection();          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDiscografica;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<Discografica> cmbDiscograficas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlbumes;
    private javax.swing.JLabel lblDiscograficas;
    private javax.swing.JList lstArtistas;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
