package vistas;

import modelo.*;

public class FormularioAlbumes extends javax.swing.JInternalFrame {

    Spotify s;

    public FormularioAlbumes(Spotify s) {
        this.s = s;
        initComponents();
        this.lstAlbumes.setListData(this.s.getAlbumes().toArray());
        
        for (Artista a : this.s.getArtistas())
            this.cmbArtistas.addItem(a);
        
        this.cmbArtistas.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstAlbumes = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbArtistas = new javax.swing.JComboBox<>();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Gestión de álbumes");

        lstAlbumes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAlbumes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                albumSeleccionado(evt);
            }
        });
        jScrollPane1.setViewportView(lstAlbumes);

        jLabel1.setText("Nombre");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAlbum(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAlbum(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        jLabel2.setText("Artista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar))
                            .addComponent(txtNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbArtistas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(cmbArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo)
                    .addComponent(btnEliminar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarAlbum(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAlbum
        // si la lista está vacía
        if (this.lstAlbumes.isSelectionEmpty()) {
            // creo un artista
            this.s.crearAlbum(this.txtNombre.getText(), (Artista) this.cmbArtistas.getSelectedItem());
        } else {
            // modifico un artista
            Album al = (Album) this.lstAlbumes.getSelectedValue();                
            this.s.modificarAlbum(al, this.txtNombre.getText(), (Artista) this.cmbArtistas.getSelectedItem());
        }

        limpiar();
    }//GEN-LAST:event_guardarAlbum

    private void nuevoAlbum(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAlbum
        limpiar();
    }//GEN-LAST:event_nuevoAlbum

    private void albumSeleccionado(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_albumSeleccionado
        // verificamos que la lista tenga un item seleccionado
        if (! this.lstAlbumes.isSelectionEmpty()) {
            // obtengo el item seleccionado
            Album al = (Album) this.lstAlbumes.getSelectedValue();
            // asigno los valores de los atributos a los componentes
            this.txtNombre.setText( al.getNombre() );
            this.cmbArtistas.setSelectedItem( al.getArtista() );
        }
    }//GEN-LAST:event_albumSeleccionado

    private void limpiar() {
        // limpio las cajas de texto
        this.txtNombre.setText("");
        this.cmbArtistas.setSelectedItem(null);
        System.out.println("Refrescar...");
        Spotify.getPersistencia().refrescar(this.s);
        System.out.println("Refrescado");
        // pueblo la lista
        this.lstAlbumes.setListData(this.s.getAlbumes().toArray());        
        // deselecciono la lista
        this.lstAlbumes.clearSelection();          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<Artista> cmbArtistas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstAlbumes;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
